In [72]:
import numpy as np
import matplotlib.pyplot as plt

In [73]:
# Load Data
data = np.loadtxt('ex1data2.txt', delimiter=',')
X = data[:, :2]
y = data[:, 2]
m = y.T.size

In [74]:
X_ = np.concatenate((np.ones((len(y), 1)), X), axis=1)

In [75]:
X_[0]


array([  1.00000000e+00,   2.10400000e+03,   3.00000000e+00])

In [76]:
y

array([ 399900.,  329900.,  369000.,  232000.,  539900.,  299900.,
        314900.,  198999.,  212000.,  242500.,  239999.,  347000.,
        329999.,  699900.,  259900.,  449900.,  299900.,  199900.,
        499998.,  599000.,  252900.,  255000.,  242900.,  259900.,
        573900.,  249900.,  464500.,  469000.,  475000.,  299900.,
        349900.,  169900.,  314900.,  579900.,  285900.,  249900.,
        229900.,  345000.,  549000.,  287000.,  368500.,  329900.,
        314000.,  299000.,  179900.,  299900.,  239500.])

In [80]:
print(X.shape)
print(X.T.dot(X)
np.linalg.inv(X.T.dot(X))

(47, 2)


array([[  5.00099792e-08,  -3.14370346e-05],
       [ -3.14370346e-05,   2.17658068e-02]])